name: instaclone
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  intl: ^0.16.0
  url_launcher: ^5.4.2
  translator: ^0.1.4
  camera: ^0.5.7+4
  path: ^1.6.4
  path_provider: ^1.6.5
  image_picker: ^0.6.4
  photofilters: ^1.0.5
  image: ^2.1.4
  diacritic: ^0.1.1
  uuid: ^2.0.4
  location: ^3.0.2
  geolocator: ^5.3.1
  flutter_widgets: ^0.1.12
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1

  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo.png
   - assets/icons/activity.png
   - assets/icons/camera.png
   - assets/icons/camera_bold.png
   - assets/icons/camera_change.png
   - assets/icons/microphone.png
   - assets/icons/loop.png
   - assets/icons/message.png
   - assets/icons/comment.png
   - assets/icons/fav.png
   - assets/icons/fav_bold.png
   - assets/icons/files.png
   - assets/icons/grid.png
   - assets/icons/home.png
   - assets/icons/home_bold.png
   - assets/icons/like.png
   - assets/icons/like_bold.png
   - assets/icons/like_red.png
   - assets/icons/menu.png
   - assets/icons/more.png
   - assets/icons/post_bold.png
   - assets/icons/post.png
   - assets/icons/profile.png
   - assets/icons/profile_bold.png
   - assets/icons/search.png
   - assets/icons/search_bold.png
   - assets/icons/timeline.png
   - assets/icons/edit_effect.png
   - assets/icons/current_location.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
